on:
  # Every pull request
  pull_request:

name: benchmarks

jobs:
  run-benchmars:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Install benchexec
        run: |
          sudo add-apt-repository ppa:sosy-lab/benchmarking
          sudo apt install benchexec
      - name: Run benchmarks
        run: sbt benchmarksReport
      - name: Generate site
        run: sbt site/benchmarksIndexUpdate site/benchmarksLongitudinalUpdate
