on:
  # Every pull request
  pull_request:

name: benchmarks

jobs:
  run-benchmars:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Install benchexec
        run: |
          sudo add-apt-repository ppa:sosy-lab/benchmarking
          sudo apt install benchexec
          # Workaround for inability to set persistant user groups
          # across shells
          sudo chmod o+wt /sys/fs/cgroup/blkio/system.slice/benchexec-cgroup.service /sys/fs/cgroup/cpu,cpuacct/system.slice/benchexec-cgroup.service /sys/fs/cgroup/cpuset/system.slice/benchexec-cgroup.service /sys/fs/cgroup/freezer/system.slice/benchexec-cgroup.service /sys/fs/cgroup/memory/system.slice/benchexec-cgroup.service
      - name: Check benchexec configuration
        run: python3 -m benchexec.check_cgroups
      - name: Run benchmarks
        run: |
          # Ensure we have the needed dirs in PATH and PYTHONPATH
          source ./.envrc
          sbt benchmarksReport
      - name: Generate site
        run: sbt site/benchmarksIndexUpdate site/benchmarksLongitudinalUpdate
