on: workflow_dispatch

name: publish-site

jobs:
  update-site:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy updated site
        # ONLY RUN IF ON TRUNK
        if: github.ref == 'refs/heads/trunk'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./src/site
